### ISSUE TITLE
main.zeek, line 98: field value missing (genisys::c$genisys_proto)

### ISSUE THREAD

**Issue by keithjjones** [cisagov/icsnpp-genisys#3]
# 🐛 Summary #

An error I ran into:

```
worker-08: expression error in <<REDACTED>>/zeek/site/packages/icsnpp-genisys/main.zeek, line 98: field value missing (genisys::c$genisys_proto)
```

This line needs to check the existence of the field c$genisys_proto before using it: https://github.com/cisagov/icsnpp-genisys/blob/main/analyzer/main.zeek#L98

**Comment by mmguero** [comment]
Resolved with #4
